networks:
  development-network:
    name: test-development-network

services:

  # Postgres Database
  postgres:
    image: postgres:${POSTGRES_TAG:-latest}
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-development}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PWD}
    command: -c shared_preload_libraries='pg_stat_statements'
    # shm_size: 128mb
    networks:
       - development-network
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB:-development}
      interval: 2s
      retries: 15
      start_period: 3s
      timeout: 1s


  # Postgres Database UI
  adminer:
    image: adminer:${ADMINER_TAG:-latest}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8085:8080
    networks:
      - development-network


  # LDES Server
  ldes-server:
    image: rorlic/ldes-server:latest
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS:-8080}
      - ConnectionStrings:Postgres=Host=postgres;Port=5432;Database=${POSTGRES_DB:-development};Username=${POSTGRES_USER};Password=${POSTGRES_PWD};Persist Security Info=true
    ports:
      - 8080:${ASPNETCORE_HTTP_PORTS:-8080}
    networks:
      - development-network
    healthcheck:
      test: curl http://ldes-server:${ASPNETCORE_HTTP_PORTS:-8080}/metrics
      interval: 2s
      retries: 15
      start_period: 3s
      timeout: 1s
